import { SectionCard } from "@/components/KpiCard";
import { PageHeader } from "@/components/PageHeader";
import {
  formatCurrency,
  getCohortRetention,
  getForecastMetrics,
  getRevenueForecast,
  getStatisticalTests,
} from "@/lib/data";

export default function AdvancedAnalyticsPage() {
  const cohorts = getCohortRetention();
  const tests = getStatisticalTests();
  const forecastMetrics = getForecastMetrics();
  const forecast = getRevenueForecast();
  const bestModel = forecastMetrics[0];
  const nextForecast = forecast[0];
  const significantTests = tests.filter((row) => row["Significant at 5%"] === "Yes").length;
  const largestCohort = cohorts.reduce((best, row) => (row["Cohort Size"] > best["Cohort Size"] ? row : best), cohorts[0]);
  const largestCohortMonth1 = Number(largestCohort["Month 1"] ?? 0);

  return (
    <>
      <PageHeader
        eyebrow="Advanced Analytics"
        title="Model Validation and Statistical Evidence"
        description="Compact proof layer for Python-generated cohort retention, statistical tests, and revenue forecast validation."
      />

      <div className="grid gap-4 xl:grid-cols-3">
        <SectionCard title="Cohort Retention" caption="Python-generated restaurant-partner retention matrix.">
          <div className="space-y-4">
            <MetricBlock label="Largest cohort" value={largestCohort["Cohort Month"]} helper={`${largestCohort["Cohort Size"].toLocaleString("en-IN")} partners`} />
            <MetricBlock label="Month-1 retention" value={`${largestCohortMonth1.toFixed(1)}%`} helper="For the largest cohort only" />
            <p className="text-xs leading-5 text-[var(--text-secondary)]">
              This proves the project tracks partner retention over time, but keeps the full retention matrix in the extract layer instead of crowding the presentation dashboard.
            </p>
          </div>
        </SectionCard>

        <SectionCard title="Statistical Tests" caption="SciPy tests generated by the Python analytics layer.">
          <div className="space-y-4">
            <MetricBlock label="Significant results" value={`${significantTests}/${tests.length}`} helper="At 5% significance" />
            <MetricBlock label="Methods used" value="Mann-Whitney + ANOVA" helper="Food category, value segment, and city comparisons" />
            <p className="text-xs leading-5 text-[var(--text-secondary)]">
              The test outputs support the story with statistical evidence without asking business viewers to read every p-value.
            </p>
          </div>
        </SectionCard>

        <SectionCard title="Forecast Validation" caption="Holdout validation from Python model comparison.">
          <div className="space-y-4">
            <MetricBlock label="Best model" value={bestModel.Model} helper={`${bestModel["MAPE (%)"].toFixed(2)}% MAPE`} />
            <MetricBlock label={`Next forecast: ${nextForecast.Month}`} value={formatCurrency(nextForecast["Forecast Revenue (INR)"])} helper={`Selected model: ${nextForecast["Selected Model"]}`} />
            <p className="text-xs leading-5 text-[var(--text-secondary)]">
              ARIMA, naive baseline, and moving average are compared in Python; this page only presents the selected validation outcome.
            </p>
          </div>
        </SectionCard>
      </div>
    </>
  );
}

function MetricBlock({ label, value, helper }: { label: string; value: string; helper: string }) {
  return (
    <div className="rounded-xl border border-[var(--border-subtle)] bg-[var(--bg-card-hover)] p-4">
      <p className="text-[11px] font-semibold uppercase tracking-wide text-[var(--text-secondary)]">{label}</p>
      <p className="mt-2 text-xl font-semibold text-[var(--text-primary)]">{value}</p>
      <p className="mt-1 text-xs text-[var(--text-secondary)]">{helper}</p>
    </div>
  );
}
